language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - bash ./build-doc.sh
  - travis_retry composer self-update
  - travis_retry composer run-script post-root-package-install
  - travis_retry composer install --prefer-source --no-interaction --dev

script: ./vendor/bin/phpspec run

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
